version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: orderdb
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,CONTROLLER_INTERNAL://0.0.0.0:9094,BROKER://0.0.0.0:9092,BROKER_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://localhost:9092,BROKER_INTERNAL://kafka:29092,CONTROLLER://localhost:9093,CONTROLLER_INTERNAL://kafka:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER,CONTROLLER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,CONTROLLER_INTERNAL:PLAINTEXT,BROKER:PLAINTEXT,BROKER_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTIONAL_ID_EXPIRATION_MS: 10000
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  mongodb_data:
  redis_data:
  kafka_data: